CREATE TABLE TB_POPLTN_DATA (
    ADMINIST_ZONE VARCHAR(150),
    TOT_POPLTN_CO INT(10),
    AGE_SCTN_POPLTN_CO INT(10),
    POPLTN_CO_0_9 INT(10),
    POPLTN_CO_10_19 INT(10),
    POPLTN_CO_20_29 INT(10),
    POPLTN_CO_30_39 INT(10),
    POPLTN_CO_40_49 INT(10),
    POPLTN_CO_50_59 INT(10),
    POPLTN_CO_60_69 INT(10),
    POPLTN_CO_70_79 INT(10),
    POPLTN_CO_80_89 INT(10),
    POPLTN_CO_90_99 INT(10),
    POPLTN_CO_100 INT(10),
    MALE_TOT_POPLTN_CO INT(10),
    MALE_AGE_SCTN_POPLTN_CO INT(10),
    MALE_POPLTN_CO_0_9 INT(10),
    MALE_POPLTN_CO_10_19 INT(10),
    MALE_POPLTN_CO_20_29 INT(10),
    MALE_POPLTN_CO_30_39 INT(10),
    MALE_POPLTN_CO_40_49 INT(10),
    MALE_POPLTN_CO_50_59 INT(10),
    MALE_POPLTN_CO_60_69 INT(10),
    MALE_POPLTN_CO_70_79 INT(10),
    MALE_POPLTN_CO_80_89 INT(10),
    MALE_POPLTN_CO_90_99 INT(10),
    MALE_POPLTN_CO_100 INT(10),
    FEMALE_TOT_POPLTN_CO INT(10),
    FEMALE_AGE_SCTN_POPLTN_CO INT(10),
    FEMALE_POPLTN_CO_0_9 INT(10),
    FEMALE_POPLTN_CO_10_19 INT(10),
    FEMALE_POPLTN_CO_20_29 INT(10),
    FEMALE_POPLTN_CO_30_39 INT(10),
    FEMALE_POPLTN_CO_40_49 INT(10),
    FEMALE_POPLTN_CO_50_59 INT(10),
    FEMALE_POPLTN_CO_60_69 INT(10),
    FEMALE_POPLTN_CO_70_79 INT(10),
    FEMALE_POPLTN_CO_80_89 INT(10),
    FEMALE_POPLTN_CO_90_99 INT(10),
    FEMALE_POPLTN_CO_100 INT(10)
);
SELECT * from TB_POPLTN_DATA;

# 성별 (남:1 , 여:2, 총합:3)
# 나이대(1: 10대미만, 2: 20대미만, 3:30대 미만,...,11: 100대)


CREATE TABLE TB_POPLTN (
  ADMINIST_ZONE_NO VARCHAR(10),
  ADMINIST_ZONE_NM VARCHAR(150),
  STD_MT VARCHAR(6),
  POPLTN_SE_CD VARCHAR(1),
  AGRDE_SE_CD VARCHAR(3),
  POPLTN_CNT INT(10),
  CONSTRAINT TB_POPLTN_PK PRIMARY KEY (ADMINIST_ZONE_NO, STD_MT, POPLTN_SE_CD, AGRDE_SE_CD)
);

INSERT INTO TB_POPLTN
SELECT A.ADMINIST_ZONE_NO, A.ADMINIST_ZONE_NM, A.STD_MT
     , CASE WHEN LVL1 = 1 THEN 'M' WHEN LVL1 = 2 THEN 'F' WHEN LVL1 = 3 THEN 'T' END AS POPLTN_SE_CD
     , CASE WHEN LVL2 = 1  THEN '000' WHEN LVL2 = 2  THEN '010' WHEN LVL2 = 3  THEN '020'
            WHEN LVL2 = 4  THEN '030' WHEN LVL2 = 5  THEN '040' WHEN LVL2 = 6  THEN '050'
            WHEN LVL2 = 7  THEN '060' WHEN LVL2 = 8  THEN '070' WHEN LVL2 = 9  THEN '080' WHEN LVL2 = 10 THEN '090' WHEN LVL2 = 11 THEN '100' END AS AGRDE_SE_CD
     , CASE WHEN LVL1 = 1 AND LVL2 = 1  THEN MALE_POPLTN_CO_0_9     WHEN LVL1 = 1 AND LVL2 = 2  THEN MALE_POPLTN_CO_10_19
            WHEN LVL1 = 1 AND LVL2 = 3  THEN MALE_POPLTN_CO_20_29   WHEN LVL1 = 1 AND LVL2 = 4  THEN MALE_POPLTN_CO_30_39
            WHEN LVL1 = 1 AND LVL2 = 5  THEN MALE_POPLTN_CO_40_49   WHEN LVL1 = 1 AND LVL2 = 6  THEN MALE_POPLTN_CO_50_59
            WHEN LVL1 = 1 AND LVL2 = 7  THEN MALE_POPLTN_CO_60_69   WHEN LVL1 = 1 AND LVL2 = 8  THEN MALE_POPLTN_CO_70_79
            WHEN LVL1 = 1 AND LVL2 = 9  THEN MALE_POPLTN_CO_80_89   WHEN LVL1 = 1 AND LVL2 = 10 THEN MALE_POPLTN_CO_90_99
            WHEN LVL1 = 1 AND LVL2 = 11 THEN MALE_POPLTN_CO_100     WHEN LVL1 = 2 AND LVL2 = 1  THEN FEMALE_POPLTN_CO_0_9
            WHEN LVL1 = 2 AND LVL2 = 2  THEN FEMALE_POPLTN_CO_10_19 WHEN LVL1 = 2 AND LVL2 = 3  THEN FEMALE_POPLTN_CO_20_29
            WHEN LVL1 = 2 AND LVL2 = 4  THEN FEMALE_POPLTN_CO_30_39 WHEN LVL1 = 2 AND LVL2 = 5  THEN FEMALE_POPLTN_CO_40_49
            WHEN LVL1 = 2 AND LVL2 = 6  THEN FEMALE_POPLTN_CO_50_59 WHEN LVL1 = 2 AND LVL2 = 7  THEN FEMALE_POPLTN_CO_60_69
            WHEN LVL1 = 2 AND LVL2 = 8  THEN FEMALE_POPLTN_CO_70_79 WHEN LVL1 = 2 AND LVL2 = 9  THEN FEMALE_POPLTN_CO_80_89
            WHEN LVL1 = 2 AND LVL2 = 10 THEN FEMALE_POPLTN_CO_90_99 WHEN LVL1 = 2 AND LVL2 = 11 THEN FEMALE_POPLTN_CO_100
            WHEN LVL1 = 3 AND LVL2 = 1  THEN POPLTN_CO_0_9          WHEN LVL1 = 3 AND LVL2 = 2  THEN POPLTN_CO_10_19
            WHEN LVL1 = 3 AND LVL2 = 3  THEN POPLTN_CO_20_29        WHEN LVL1 = 3 AND LVL2 = 4  THEN POPLTN_CO_30_39
            WHEN LVL1 = 3 AND LVL2 = 5  THEN POPLTN_CO_40_49        WHEN LVL1 = 3 AND LVL2 = 6  THEN POPLTN_CO_50_59
            WHEN LVL1 = 3 AND LVL2 = 7  THEN POPLTN_CO_60_69        WHEN LVL1 = 3 AND LVL2 = 8  THEN POPLTN_CO_70_79
            WHEN LVL1 = 3 AND LVL2 = 9  THEN POPLTN_CO_80_89        WHEN LVL1 = 3 AND LVL2 = 10 THEN POPLTN_CO_90_99
            WHEN LVL1 = 3 AND LVL2 = 11 THEN POPLTN_CO_100 END AS POPLTN_CNT
  FROM
     (
      SELECT SUBSTR(ADMINIST_ZONE, INSTR(ADMINIST_ZONE, '(') + 1, 10) AS ADMINIST_ZONE_NO
           , SUBSTR(ADMINIST_ZONE, 1, INSTR(ADMINIST_ZONE, '(')-1) AS ADMINIST_ZONE_NM,
             '202304' AS STD_MT
           , MALE_POPLTN_CO_0_9    , MALE_POPLTN_CO_10_19  , MALE_POPLTN_CO_20_29
           , MALE_POPLTN_CO_30_39  , MALE_POPLTN_CO_40_49  , MALE_POPLTN_CO_50_59
           , MALE_POPLTN_CO_60_69  , MALE_POPLTN_CO_70_79  , MALE_POPLTN_CO_80_89  , MALE_POPLTN_CO_90_99  , MALE_POPLTN_CO_100
           , FEMALE_POPLTN_CO_0_9  , FEMALE_POPLTN_CO_10_19, FEMALE_POPLTN_CO_20_29
           , FEMALE_POPLTN_CO_30_39, FEMALE_POPLTN_CO_40_49, FEMALE_POPLTN_CO_50_59
           , FEMALE_POPLTN_CO_60_69, FEMALE_POPLTN_CO_70_79, FEMALE_POPLTN_CO_80_89, FEMALE_POPLTN_CO_90_99, FEMALE_POPLTN_CO_100
           , POPLTN_CO_0_9         , POPLTN_CO_10_19, POPLTN_CO_20_29
           , POPLTN_CO_30_39       , POPLTN_CO_40_49, POPLTN_CO_50_59
           , POPLTN_CO_60_69       , POPLTN_CO_70_79, POPLTN_CO_80_89, POPLTN_CO_90_99, POPLTN_CO_100
           , LVL1, LVL2
        FROM TB_POPLTN_DATA, (SELECT (tmp1.idx) AS LVL1 FROM (SELECT 1 as idx UNION SELECT 2 UNION SELECT 3) tmp1) LVL1, (SELECT (tmp2.idx) AS LVL2 FROM (SELECT 1 as idx UNION SELECT 2 UNION SELECT 3 UNION SELECT 4 UNION SELECT 5 UNION SELECT 6 UNION SELECT 7 UNION SELECT 8 UNION SELECT 9 UNION SELECT 10 UNION SELECT 11) tmp2) LVL2
     ) A ;
COMMIT;

# 2023년 4월 기준 전국의 성별 인구수 합계 구히여, 여성/남성 비율 구해보기
SELECT * FROM TB_POPLTN;
SELECT A.POPLTN_SE_CD, 
		SUM(A.POPLTN_CNT)
FROM TB_POPLTN A
WHERE A.ADMINIST_ZONE_NO LIKE '__00000000'
AND A.POPLTN_SE_CD IN ('F','M')
AND A.STD_MT = '202304'
GROUP BY A.POPLTN_SE_CD;

# 이제 성비를 구해야함.
# 그러려먼  F, M이 세로가 아닌 가로로 있는게 더 편하지 않을까?

# 1) 남녀 인구수 합계-> 각 컬럼으로 계산하기

SELECT A.POPLTN_SE_CD, 
		-- SUM(A.POPLTN_CNT)
        CASE 
			WHEN A.POPLTN_SE_CD = 'M' THEN SUM(A.POPLTN_CNT)
            ELSE 0
		END AS MALE_AGRDE_POPLTN_CNT,
        
        CASE 
			WHEN A.POPLTN_SE_CD = 'F' THEN SUM(A.POPLTN_CNT)
            ELSE 0
		END AS MALE_AGRDE_POPLTN_CNT
FROM TB_POPLTN A
WHERE A.ADMINIST_ZONE_NO LIKE '__00000000'
AND A.POPLTN_SE_CD IN ('F','M')
AND A.STD_MT = '202304'
GROUP BY A.POPLTN_SE_CD;


# 2) 남녀 비율 구하기
SELECT B.MALE_AGRDE_POPLTN_CNT AS "남자 인구수",
		B.FEMALE_AGRDE_POPLTN_CNT AS "여자 인구수",
        ROUND(B.MALE_AGRDE_POPLTN_CNT/B.FEMALE_AGRDE_POPLTN_CNT,4)*100 AS '남자/여자 비율', -- 남자/여자
		ROUND(B.MALE_AGRDE_POPLTN_CNT/(B.MALE_AGRDE_POPLTN_CNT+B.FEMALE_AGRDE_POPLTN_CNT)*100,4) AS '전체 인구수 대비 남자 비율',
        ROUND(B.FEMALE_AGRDE_POPLTN_CNT/(B.MALE_AGRDE_POPLTN_CNT+B.FEMALE_AGRDE_POPLTN_CNT)*100,4) AS '전체 인구수 대비 여자 비율'
FROM
(
	SELECT MAX(MALE_AGRDE_POPLTN_CNT) AS MALE_AGRDE_POPLTN_CNT,
		MAX(FEMALE_AGRDE_POPLTN_CNT) AS FEMALE_AGRDE_POPLTN_CNT     
	FROM (
		SELECT A.POPLTN_SE_CD, 
			-- SUM(A.POPLTN_CNT)
			CASE 
				WHEN A.POPLTN_SE_CD = 'M' THEN SUM(A.POPLTN_CNT)
				ELSE 0
			END AS MALE_AGRDE_POPLTN_CNT,
			
			CASE 
				WHEN A.POPLTN_SE_CD = 'F' THEN SUM(A.POPLTN_CNT)
				ELSE 0
			END AS FEMALE_AGRDE_POPLTN_CNT
	FROM TB_POPLTN A
	WHERE A.ADMINIST_ZONE_NO LIKE '__00000000'
	AND A.POPLTN_SE_CD IN ('F','M')
	AND A.STD_MT = '202304'
	GROUP BY A.POPLTN_SE_CD) AS A) AS B
;


use sql_analyze;
SELECT * FROM TB_POPLTN;

-- ----------------------------------------------------------------------------------------
# 2023년 04월 기준 전국 주요 시/도의 연령대별 인구 수 합계
-- ----------------------------------------------------------------------------------------
SELECT * FROM TB_POPLTN;
SELECT AGRDE_SE_CD, 
		SUM(POPLTN_CNT) AGRDE_POPLTN_CNT 
FROM TB_POPLTN
WHERE ADMINIST_ZONE_NO LIKE '__00000000'
AND POPLTN_SE_CD = 'T' -- 전체 인구
AND STD_MT = '202304'
GROUP BY AGRDE_SE_CD
ORDER BY AGRDE_SE_CD;

-- ------------------------------------------------------------------------------------------
# 2023년 4월 기준 전국 주요 시/도의 연령대별 인구수 합계를 구하고, 연령대별 인구 비율 구하기
-- ------------------------------------------------------------------------------------------
SELECT * FROM TB_POPLTN;

SELECT AGRDE_SE_CD, SUM(POPLTN_CNT) as sum_pop
FROM TB_POPLTN
WHERE ADMINIST_ZONE_NO LIKE '__00000000'
	AND POPLTN_SE_CD  = 'T'
	GROUP BY AGRDE_SE_CD
ORDER BY AGRDE_SE_CD;

-- -------------------------------------------------------------------------------------------
# 2023년 4울 기준 전국 주요 시.도의 연령대별 인구수 합계를 구하고, 연령대별 인구 비율 구하기
-- -------------------------------------------------------------------------------------------
SELECT A.AGRDE_SE_CD,
		A.AGRDE_POPLTN_CNT,
        SUM(A.AGRDE_POPLTN_CNT) OVER() AS SUM_AGRDE_POPLTN_CNT
FROM(SELECT A.AGRDE_SE_CD, 
			SUM(A.POPLTN_CNT) as AGRDE_POPLTN_CNT
		FROM TB_POPLTN A
		WHERE A.ADMINIST_ZONE_NO LIKE '__00000000'
			AND A.POPLTN_SE_CD  = 'T'
			AND A.STD_MT = '202304'
			GROUP BY A.AGRDE_SE_CD
		ORDER BY A.AGRDE_SE_CD) AS A;
        
-- --------------------------------------------------------------------------------------------
# 연령대별 인구가 가장 많은 지역 구하기(읍/면/동)
-- --------------------------------------------------------------------------------------------
SELECT A.AGRDE_SE_CD,
		A.ADMINIST_ZONE_NO,
        A.ADMINIST_ZONE_NM,
        A.POPLTN_CNT
FROM TB_POPLTN A
WHERE A.ADMINIST_ZONE_NO NOT LIKE '_____00000' # 앞 다섯자리는 시군구까지의 코드. 동까지 보려면 뒤 5자리가 0이면 안됨.
 AND A.POPLTN_SE_CD = 'T'
 AND A.STD_MT = '202304'
 AND A.POPLTN_CNT > 0
ORDER BY A.POPLTN_CNT DESC;

SELECT A.AGRDE_SE_CD,
		A.ADMINIST_ZONE_NO,
		A.ADMINIST_ZONE_NM,
		A.POPLTN_CNT
FROM(
	SELECT  A.AGRDE_SE_CD,
		A.ADMINIST_ZONE_NO,
		A.ADMINIST_ZONE_NM,
		A.POPLTN_CNT,
        ROW_NUMBER() OVER(PARTITION BY A.AGRDE_SE_CD ORDER BY A.POPLTN_CNT DESC) AS RNUM
        
	FROM (
		SELECT A.AGRDE_SE_CD,
				A.ADMINIST_ZONE_NO,
				A.ADMINIST_ZONE_NM,
				A.POPLTN_CNT
		FROM TB_POPLTN A
		WHERE A.ADMINIST_ZONE_NO NOT LIKE '_____00000' # 앞 다섯자리는 시군구까지의 코드. 동까지 보려면 뒤 5자리가 0이면 안됨.
		 AND A.POPLTN_SE_CD = 'T'
		 AND A.STD_MT = '202304'
		 AND A.POPLTN_CNT > 0
		ORDER BY A.POPLTN_CNT DESC) A
) A
WHERE A.RNUM = 1
ORDER BY A.AGRDE_SE_CD ASC;

-- --------------------------------------------------------------------------------------------
# 2023년 04월 기준 전국의 각 지역의 연령대별 인구수 비율이 높은 지역(읍/면/동)
-- --------------------------------------------------------------------------------------------
#1) 읍면동별, 연령대별 인구
SELECT *
		FROM TB_POPLTN 
		WHERE ADMINIST_ZONE_NO NOT LIKE '_____00000' -- 읍면동만 뽑은 것
		 AND POPLTN_SE_CD = 'T'
		 AND STD_MT = '202304'
		 AND POPLTN_CNT >0
;

#2) 연령대별 총 인구
SELECT * FROM TB_POPLTN;

SELECT *
FROM (SELECT AGRDE_SE_CD,
			SUM(POPLTN_CNT) AS AGE_CNT_TOTAL
		FROM TB_POPLTN 
		WHERE ADMINIST_ZONE_NO NOT LIKE '_____00000' -- 읍면동만 뽑은 것
		AND POPLTN_SE_CD = 'T'
		AND STD_MT = '202304'
		AND POPLTN_CNT >0
		GROUP BY AGRDE_SE_CD) AS A
;

#3) 1+2 JOIN
SELECT A.AGRDE_SE_CD,
		A.AGE_CNT_TOTAL,
        B.ADMINIST_ZONE_NM,
        B.POPLTN_CNT,
        (B.POPLTN_CNT/A.AGE_CNT_TOTAL) as ratio
        
FROM (SELECT AGRDE_SE_CD,
			SUM(POPLTN_CNT) AS AGE_CNT_TOTAL
		FROM TB_POPLTN 
		WHERE ADMINIST_ZONE_NO NOT LIKE '_____00000' -- 읍면동만 뽑은 것
		AND POPLTN_SE_CD = 'T'
		AND STD_MT = '202304'
		AND POPLTN_CNT >0
		GROUP BY AGRDE_SE_CD) AS A

JOIN TB_POPLTN B ON B.AGRDE_SE_CD = A.AGRDE_SE_CD
WHERE B.ADMINIST_ZONE_NO NOT LIKE '_____00000'
AND B.POPLTN_SE_CD = 'T'
AND B.STD_MT = '202304'
AND B.POPLTN_CNT >0
        ;
# 4) 정답
SELECT C.AGRDE_SE_CD,
		C.ADMINIST_ZONE_NM,
        C.AGE_CNT_TOTAL,
		C.POPLTN_CNT,
		C.ratio,
		C.RNUM
FROM
	(SELECT 
			B.AGRDE_SE_CD,
			B.AGE_CNT_TOTAL,
			B.ADMINIST_ZONE_NM,
			B.POPLTN_CNT,
			B.ratio,
		   ROW_NUMBER() OVER(PARTITION BY B.AGRDE_SE_CD ORDER BY B.ratio DESC) AS RNUM
	FROM(
			SELECT A.AGRDE_SE_CD,
					A.AGE_CNT_TOTAL,
					B.ADMINIST_ZONE_NM,
					B.POPLTN_CNT,
					(B.POPLTN_CNT/A.AGE_CNT_TOTAL) as ratio
				
			FROM (
					SELECT AGRDE_SE_CD,
							SUM(POPLTN_CNT) AS AGE_CNT_TOTAL -- 연령대별 총 인구수
					FROM TB_POPLTN 
					WHERE ADMINIST_ZONE_NO NOT LIKE '_____00000' -- 읍면동만 뽑은 것
					AND POPLTN_SE_CD = 'T'
					AND STD_MT = '202304'
					AND POPLTN_CNT >0
					GROUP BY AGRDE_SE_CD) AS A

			JOIN TB_POPLTN B ON B.AGRDE_SE_CD = A.AGRDE_SE_CD
			WHERE B.ADMINIST_ZONE_NO NOT LIKE '_____00000'
			AND B.POPLTN_SE_CD = 'T'
			AND B.STD_MT = '202304'
			AND B.POPLTN_CNT >0
		) B
	) C
WHERE C.RNUM = 1
;

# 5) 찐 정답 by강사님
# 4) 정답
SELECT A.AGRDE_SE_CD, A.ADMINIST_ZONE_NO, A.ADMINIST_ZONE_NM, A.POPLTN_CNT, A.`행정구역번호별각연령대의인구수가차지하는비율`, A.RNUM
FROM
   (
    SELECT A.AGRDE_SE_CD
         , A.ADMINIST_ZONE_NO
         , A.ADMINIST_ZONE_NM
         , A.POPLTN_CNT
         , A.`행정구역번호별각연령대의인구수가차지하는비율`
         , ROW_NUMBER() OVER(PARTITION BY A.AGRDE_SE_CD ORDER BY A.`행정구역번호별각연령대의인구수가차지하는비율` DESC)
             AS RNUM
      FROM
         (
            SELECT
                   A.AGRDE_SE_CD
                 , A.ADMINIST_ZONE_NO
                 , A.ADMINIST_ZONE_NM
                 , A.POPLTN_CNT
                 , ROUND((POPLTN_CNT / SUM(A.POPLTN_CNT) OVER(PARTITION BY ADMINIST_ZONE_NO)) * 100, 2)
                     AS `행정구역번호별각연령대의인구수가차지하는비율`
              FROM
                 (
                    SELECT
                           A.AGRDE_SE_CD
                         , A.ADMINIST_ZONE_NO
                         , A.ADMINIST_ZONE_NM
                         , A.POPLTN_CNT
                      FROM TB_POPLTN A
                     WHERE A.ADMINIST_ZONE_NO NOT LIKE '_____00000'
                       AND A.POPLTN_SE_CD IN ('T')
                       AND A.POPLTN_CNT > 0
                       AND A.STD_MT = '202304'
                     ORDER BY POPLTN_CNT DESC
             ) A
        ) A
    ) A
 WHERE RNUM = 1;